<?php

namespace Varena\SDK\Request;

use Varena\SDK\Request\Traits\AuthTrait;
use Varena\SDK\Request\Traits\VarenaRequestTrait;

/**
 * Class VarenaRequest
 * @package Varena\SDK\Request
 * Author: JV
 */
class VarenaRequest extends AbstractRequest
{
    use VarenaRequestTrait;
    use AuthTrait;

    protected static $_instance = null;
    protected static $_key = null;
    protected static $_secert = null;

    /**
     * @var
     */
    protected $baseUri = 'http://api.varena.com/';

    public function __construct(string $key,string $sercert)
    {
        self::$_key = $key;
        self::$_secert = $sercert;
        parent::__construct();
    }

    /***
     * @param string $uri
     * @param array $params
     * @return array
     * Author: JV
     */
    public function getData($uri, array $params = [])
    {
        $this->setExtraRequestOptions(self::$_key,$uri,$params,self::$_secert);
        return parent::getData($uri, $params); // TODO: Change the autogenerated stub
    }

    /***
     * @param string $uri
     * @param array $params
     * @return array
     * Author: JV
     */
    public function postData($uri, $params = [])
    {
        $this->setExtraRequestOptions(self::$_key,$uri,$params,self::$_secert);
        return parent::postData($uri, $params); // TODO: Change the autogenerated stub
    }
}
